name: Context
on: [ push, pull_request]

jobs:
  function:
    runs-on: ubuntu-latest
    steps:
      - name: dump
        run: |
          echo ${{ contains( 'hello', 'll') }}
          echo ${{ startsWith( 'hello', 'he') }}
          echo ${{ endsWith( 'hello', 'lo') }}
          echo ${{ format( 'Hello {0} {1} {2}', 'you', 'and', 'me') }}
  one:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: eccho "$GITHUB_CONTEXT"
      - name: Dump job context
        if: failure()
        env:
          JOB_CONTEXT: ${{ toJSON(job) }}
        run: echo "$JOB_CONTEXT"
      - name: Dump steps context
        if: success()
        env:
          STEPS_CONTEXT: ${{ toJSON(steps) }}
        run: eccho "$STEPS_CONTEXT"
      - name: Dump runner context
        if: always()
        env:
          RUNNER_CONTEXT: ${{ toJSON(runner) }}
        run: echo "$RUNNER_CONTEXT"
      - name: Dump strategy context
        env:
          STRATEGY_CONTEXT: ${{ toJSON(strategy) }}
        run: echo "$STRATEGY_CONTEXT"
      - name: Dump matrix context
        env:
          MATRIX_CONTEXT: ${{ toJSON(matrix) }}
        run: echo "$MATRIX_CONTEXT"
