name: Container
on: push

jobs: 
  docker-steps:
    runs-on: ubuntu-latest
    container:
      image: node:10.18.0-jessie
    steps:
      - name: log node version
        run: node -v
      - name: Step with Docker
        uses: docker://node:12.14.1-alpine3.10
        with: 
          entrypoint: '/bin/echo'
          args: 'Hello'
      - name: Log node version
        uses: docker://node:12.14.1-alpine3.10
        if: always()
        with: 
          entrypoint: /usr/local/bin/node
          args: -v
      - uses: actions/checkout@v2
      - name: Custom script
        uses: docker://node:12.14.1-alpine3.10
        if: always()
        with: 
          entrypoint: ./script.sh
          args: "Some string"    
      - name: Send a docker image
        uses: docker://technosophos/slack-notify 
        env:  
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_MESSAGE: 'Hallo Slack'
  node-docker:
    runs-on: ubuntu-latest
    services: 
      app:
        image: alialaa17/node-api
        ports:
          - 3001:3000
      mongo:
        image: mongo
        ports:
          - "27017:27017"
    steps: 
      - name: Get users1
        run: curl http://localhost:3001/api/users
      - name: Post a user
        run: "curl -X POST http://localhost:3001/api/user -H 'Content-Type: application/json' -d '{\"username\": \"hello\", \"address\": \"dwdw\"}'"
      - name: Get users2
        run: curl http://localhost:3001/api/users
